### ISSUE TITLE
Proposal to change skillmap structure

### ISSUE THREAD

**Issue by eeegl** [pQBL/course-template#13]
I noticed some problems with the way we structure the skillmap, which could use some looking over in the future.
This is what I came up with, please feel free to add any thoughts.

### Problems
1. The skillmap + parsing depends on explicit ordering. When parsing each unit in `skillmap.yaml`, if the numbering of `page_x` does not start at `1` (i.e. `page_1`), it will be skipped during parsing in [`qbl_bot_pipeline.py`](https://github.com/pQBL/qbl-bot-pipeline/blob/main/qbl_bot_pipeline.py#L18-L29).
2. It seems unnecessary for the user to have to keep track of which strings need quoting and which do not.

### Solutions
1. Change to implicit ordering in the form of a list (instead of an object with explicit ordering in key names) for units/pages in `skillmap.yaml`. The units/pages can then be parsed in order by iterating over the corresponding list.
2. Quote all strings for simplicity and safety.

### Advantages
- **Less cognitive load for the user** since ordering is done by positioning rather than numbering, and one single way of formatting strings eliminates ambiguity.
- **More robust parsing** since there is no risk of numbering errors, and consistent string quoting catches colons.

### Comparison 
```yaml
#
# Proposed new format:
#

units: # <-- List of units removes the need for explicit numbering

- unit: "Intro to Golang & Basic Concurrency"
  pages:
    - page: "What is parallelism and concurrency?"
      skills:
        - "Understand the basics of concurrency & parallelism & sequential"
    - page: "Setting up Go"
      skills:
        - "Setup a functioning Go environment and set up Go modules"
    - page: "Tour of Go 1 (Basics)"
      skills:
        - "Understand and apply Golang fundamentals: Basic syntax"
        - "Understand and apply Golang fundamentals: Types"
        - "Understand and apply Golang fundamentals: Control structures"

- unit: "Concurrency in Golang & Bug Fixes"
  pages:
    - page: "Concurrency Coordination"
      skills:
        - "Coordinate concurrent programming and solve concurrency bugs"

#
# Old format:
#

unit_1:
  unit_name: Intro to Golang & Basic Concurrency

  page_1:
    page_name: What is parallelism and concurrency?
    skills:
      - Understand the basics of concurrency & parallelism & sequential

  page_2: 
    page_name: Setting up Go
    skills:
      - Setup a functioning Go environment and set up Go modules

  page_3:
    page_name: Tour of Go 1 (Basics)
    skills:
      - "Understand and apply Golang fundamentals: Basic syntax"
      - "Understand and apply Golang fundamentals: Types"
      - "Understand and apply Golang fundamentals: Control structures"

unit_2:
  unit_name: Concurrency in Golang & Bug Fixes

  page_1:
    page_name: Concurrency Coordination
    skills:
      - Coordinate concurrent programming and solve concurrency bugs.
```
